all:
  children:
    # Group for Raspberry Pi NAS setup
    raspberry_pi_nas:
      hosts:
        raspi_nas:
          # Basic host details
          ansible_host: "{{ nas_endpoint }}"
          ansible_user: "{{ nas_user }}"
          ansible_become_pass: "{{ nas_password }}"
          ansible_port: "{{ nas_port }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
          ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
